# Generated by Django 4.0.3 on 2022-03-04 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=255, unique=True)),
                ('rating', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='songrater.ratings', to_field='song')),
                ('artist', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='ratings',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songrater.users'),
        ),
    ]
