# Generated by Django 4.0.3 on 2022-03-04 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songrater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='song',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='songrater.ratings', to_field='song'),
        ),
    ]
