# Generated by Django 4.0.3 on 2022-03-04 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songrater', '0002_alter_artist_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='song',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='ratings',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songrater.artist'),
        ),
    ]
