# Generated by Django 4.0.3 on 2022-03-09 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songrater', '0003_alter_artist_song_alter_ratings_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistInformation',
            fields=[
                ('artist', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('birth_day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('number_of_songs', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songrater.artist')),
            ],
        ),
    ]
