# Generated by Django 4.0.3 on 2022-03-09 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songrater', '0004_artistinformation_albums'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistinformation',
            old_name='artist',
            new_name='artist_name',
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songrater.artistinformation'),
        ),
    ]
