# Generated by Django 4.0.3 on 2022-03-09 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songrater', '0005_rename_artist_artistinformation_artist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songrater.artistinformation'),
        ),
    ]
